### ISSUE TITLE
Trying to run DD  I get an error message about not finding users in project_users

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/data_dispatcher#21]
I'm trying to run my 3 months old dd test and I got it to talk to the data dispatcher. 

Is it possible that I am not on a list of valid users for production and it fails for that reason?

Here is the dump I get.  The failure seems to be in data_dispatcher/api.py

<schellma> more dd.txt
/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python
/requests/packages/urllib3/connectionpool.py:787: InsecureRequestWarning: Unverified HTTPS re
quest is being made. Adding certificate verification is strongly advised. See: https://urllib
3.readthedocs.org/en/latest/security.html
  warnings.warn((
Traceback (most recent call last):
  File "/cvmfs/larsoft.opensciencegrid.org/products/python/v3_9_13/Linux64bit+3.10-2.17/lib/p
ython3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/larsoft.opensciencegrid.org/products/python/v3_9_13/Linux64bit+3.10-2.17/lib/p
ython3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/dune/data/users/schellma/LArWrapperExample/python/DDInterface.py", line 547, in <mod
ule>
    dd_proj_id = submit_dd_jobs.create_project(dataset=args.dataset, query=args.query, namesp
ace=args.namespace,
  File "/dune/data/users/schellma/LArWrapperExample/python/submit_dd_jobs.py", line 56, in cr
eate_project
    proj_dict = dd_client.create_project(files=query_files, query=thequery, idle_timeout=2592
01)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/datadispatcher-1.26.0-py3.9.eg
g/data_dispatcher/api.py", line 179, in create_project
    return self.post("create_project", json.dumps(
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.35.0-py3.9.egg/metac
at/common/http_client.py", line 186, in post
    return self.interpret_response(response)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.35.0-py3.9.egg/metac
at/common/http_client.py", line 147, in interpret_response
    raise WebAPIError(self.LastURL, response)
metacat.common.exceptions.WebAPIError: <html><body><h2>Application error</h2>
            <h3>relation "users" does not exist
LINE 3:                 from users, project_users
                             ^
</h3>
            <pre>
Traceback (most recent call last):
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 644, in wsgi_call

**Comment by ivmfnal** [comment]
Fixed that
