### ISSUE TITLE
getresponse() got an unexpected keyword argument 'buffering'. from dd project  commands

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/data_dispatcher#5]
I am getting intermittent errors like the below  This is running on dunegpvm11.fnal.gov

dd project list sometimes succeeds but also fails ~50% of the time with the error dump below

dd version
Server URL:     https://metacat.fnal.gov:9443/dune/dd/data
Server version: 1.16.3
Client version: 1.15.2

$dd project list
Traceback (most recent call last):
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/packages/urllib3/connectionpool.py", line 557, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/cvmfs/larsoft.opensciencegrid.org/products/python/v3_9_2/Linux64bit+3.10-2.17/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/cvmfs/larsoft.opensciencegrid.org/products/python/v3_9_2/Linux64bit+3.10-2.17/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/cvmfs/larsoft.opensciencegrid.org/products/python/v3_9_2/Linux64bit+3.10-2.17/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/adapters.py", line 366, in send
    resp = conn.urlopen(
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/packages/urllib3/connectionpool.py", line 608, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/packages/urllib3/connectionpool.py", line 557, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/cvmfs/larsoft.opensciencegrid.org/products/python/v3_9_2/Linux64bit+3.10-2.17/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/cvmfs/larsoft.opensciencegrid.org/products/python/v3_9_2/Linux64bit+3.10-2.17/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/cvmfs/larsoft.opensciencegrid.org/products/python/v3_9_2/Linux64bit+3.10-2.17/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nashome/s/schellma/.local/bin/dd", line 33, in <module>
    sys.exit(load_entry_point('datadispatcher==1.16.4', 'console_scripts', 'dd')())
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/data_dispatcher/ui/ui_main.py", line 155, in main
    cli.run(sys.argv, argv0="dd")
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 205, in run
    self._run(command, context, argv, usage_on_error)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 200, in _run
    return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 200, in _run
    return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 99, in _run
    return self(command, context, opts, args)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/data_dispatcher/ui/ui_project.py", line 292, in __call__
    lst = client.list_projects(state=state, attributes=attributes, owner=owner, with_files=True, with_replicas=False)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/data_dispatcher/api.py", line 384, in list_projects
    return self.get(f"projects{args}")
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/data_dispatcher/api.py", line 89, in get
    response = self.retry_request("get", url, headers=headers)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/data_dispatcher/api.py", line 70, in retry_request
    response = requests.get(url, timeout=self.Timeout, **args)
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/cvmfs/fermilab.opensciencegrid.org/products/common/prd/python_request/v2_9_1/NULL/lib/python/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by ivmfnal** [comment]
There were problems with some of the nodes of the redundant web services infrastructure. The problem affected multiple services, including DD. The nodes had to be reset.
